Slim down KeyMapManager,  Remove keyboard-layout
Axosoft/atom-keymap pull request #1
Opened 2024-06-05 21:31 UTC by zawata

2024-06-06 19:34 UTC, Mr-Wallet approved these changes

2024-06-07 19:07 UTC, avi-gitkraken requested changes
I keep getting `Uncaught TypeError: currentLayout.indexOf is not a function` in the render console when I boot up GKD with this module.

2024-06-07 19:07 UTC, avi-gitkraken commented on package.json
> -    "electron": "^4.2.12",
Hold up, I had to install `electron`, `electron-rebuild`, and `rimraf` in order to test this module. If we're going to remove them from package.json, we should at least have better instructions about how to test this module in the readme.

2024-06-11 20:56 UTC, zawata commented on package.json
> -    "electron": "^4.2.12",
I force-pushed the last commit to update the modules needed for tests, the tests themselves, and a small bug.

2024-06-11 21:20 UTC, avi-gitkraken approved these changes

2024-06-11 21:20 UTC, merged